version: '3'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./api
    image: jorgem/pycustomer
    container_name: pycustomer-api
    env_file: pycustomer.env
    volumes:
    - ./api/feedbacks:/api/feedbacks
    - ./api/pycustomer:/api/pycustomer
    ports:
      - 9000:9000

  vue:
    build:
      context: ./front
      dockerfile: Dockerfile
    image: jorgem/pycustomer-front
    container_name: pycustomer-front
    env_file: pycustomer.env
    volumes:
      - ./front/src:/front/src
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 8000:8000
