version: '3'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./api
    image: jorgem/pycustomer
    container_name: pycustomer-api
    env_file:
      - pycustomer.env
    command: bash docker-entrypoint.sh
    volumes:
    - ./api/feedbacks:/api/feedbacks
    - ./api/pycustomer:/api/pycustomer
    ports:
      - 9000:9000
    expose:
      - 9000
    depends_on:
      - postgresql

  vue:
    build:
      context: ./front
      dockerfile: database.Dockerfile
    image: jorgem/pycustomer-front
    container_name: pycustomer-front
    env_file:
      - pycustomer.env
    command: npm run serve
    volumes:
      - ./front/src:/front/src
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    expose:
      - 8000
    depends_on:
      - api
      - postgresql

  postgresql:
    container_name: pycustomer-db
    image: postgres:12.2-alpine
    env_file:
      - pycustomer.env
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/postgresql/data:/var/lib/postgresql/data
    expose:
      - 5432
