version: "3"

services:
  api:
    build: ./api
    container_name: pycustomer-api
    restart: always
    env_file:
      - .env
    expose:
      - 8000

  vue:
    build: ./front
    container_name: pycustomer-vue
    restart: always
    env_file:
      - .env
    links:
      - api:pycustomer-api
    ports:
      - "9000:9000"
    expose:
      - 9000
